import dotenv from "dotenv";
dotenv.config();

export const {
  NODE_ENV,
  PORT,
  DB_HOST,
  DB_PORT,
  DB_USER,
  DB_PASS,
  DB_NAME,
  INTERNAL_API_BASE_URL,
  INTERNAL_API_KEY,
  AUTH_SERVICE_URL,
  NODEMAILER_USER,
  NODEMAILER_PASSWORD,
  GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET,
  GITHUB_REDIRECT_URI_DEV,
  MOBILE_SCHEME,
  FRONTEND_URL,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
} = process.env;
